// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf033tf50Exucoq2KhFuevjbIrFe59tPA',
    appId: '1:76679896135:web:83100f6c8baf09df416562',
    messagingSenderId: '76679896135',
    projectId: 'compass-9',
    authDomain: 'compass-9.firebaseapp.com',
    databaseURL: 'https://compass-9-default-rtdb.firebaseio.com',
    storageBucket: 'compass-9.appspot.com',
    measurementId: 'G-118GMBBM17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwIcV3PZ6vyvoB3km43gQiYjx0-4G65ns',
    appId: '1:76679896135:android:9479e356aa581b39416562',
    messagingSenderId: '76679896135',
    projectId: 'compass-9',
    databaseURL: 'https://compass-9-default-rtdb.firebaseio.com',
    storageBucket: 'compass-9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IYvAI6G-5QErsut8vkRGdju1PqpClc8',
    appId: '1:76679896135:ios:f4dcff275a624f58416562',
    messagingSenderId: '76679896135',
    projectId: 'compass-9',
    databaseURL: 'https://compass-9-default-rtdb.firebaseio.com',
    storageBucket: 'compass-9.appspot.com',
    androidClientId: '76679896135-teb9tq6jn707tn25rnoi6lucldlb7l57.apps.googleusercontent.com',
    iosClientId: '76679896135-skv2cr9lt9360u1dclvdq97i6h0a9bnq.apps.googleusercontent.com',
    iosBundleId: 'com.compass.compass',
  );
}
